# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop

require:
  - rubocop-capybara
  - rubocop-rspec_rails

plugins:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Include:
    - '**/*.rb'
    - '**/config.ru'
  Exclude:
    - 'Rakefile'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'client/node_modules/**/*'
    - 'bin/**/*'
    - 'bundler_stubs/**/*'
    - 'config/locales/plurals.rb'

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/ModuleLength:
  Max: 300

Metrics/ParameterLists:
  Max: 10

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Exclude:
    - Capfile
    - Gemfile

RSpec:
  Enabled: true