language: ruby
cache:
  bundler: true
  directories:
    - 'node_modules'
    - 'client/node_modules'
env:
  global:
  - CODECLIMATE_REPO_TOKEN=783e4ac8cc44be68f2be2932fb13e2805e1f21b4541d689c9c7fe12bfb2373fb
script:
  - bundle exec rake db:structure:load
  - nvm install 10.17.0
  - npm install
  - cd client
  - npm install
  - npm prune
  - npm run build:client
  - npm run build:server
  - cd ..
  - bundle exec rake lint
  - bundle exec rspec
rvm:
  - 2.4
addons:
  postgresql: '9.5'
  chrome: stable
services:
  - redis-server
before_script:
  - cp config/database.yml.travis config/database.yml
before_install:
  - 'echo ''install: --no-rdoc --no-ri --no-document --suggestions'' >> ~/.gemrc'
  - 'echo ''update: --no-rdoc --no-ri --no-document --suggestions'' >> ~/.gemrc'
  - bundle config git.allow_insecure true
  - wget https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d $HOME/bin
  - export PATH=$HOME/bin:$PATH
bundler_args:
  --without development production -j5 --retry 10