services:
  postgres:
    image: mpugach/postgres_ua:9.5
    platform: linux/amd64
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: va_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:3.2.12-alpine
    platform: linux/amd64
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    command: redis-server --appendonly yes

  app:
    platform: linux/amd64
    build:
      context: "."
      dockerfile: docker/akadem_students/Dockerfile
      target: development
    platform: linux/amd64
    ports:
      - 3000:3000
    volumes:
      - .:/home/app/students_crm
      - assets-javascript-generated:/home/app/students_crm/app/assets/javascripts/generated
      - bundle:/usr/local/bundle
      - client-node-modules:/home/app/students_crm/client/node_modules
      - node-modules:/home/app/students_crm/node_modules
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    environment:
      REDIS_URL: redis
      RAILS_ENV: development
    entrypoint: /home/app/students_crm/bin/start_dev.sh

volumes:
  assets-javascript-generated:
  bundle:
  client-node-modules:
  node-modules:
  postgres-data:
  redis-data:
