version: '3.7'

services:
  postgres:
    image: mpugach/postgres_ua:9.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: va_db
      POSTGRES_USER: postgres

  redis:
    image: redis:3.2.12-alpine

  application:
    build:
      context: '.'
      dockerfile: docker/akadem_students/Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - .:/home/app/students_crm
      - assets-javascript-generated:/home/app/students_crm/app/assets/javascript/generated
      - bundle:/usr/local/bundle
      - client-node-modules:/home/app/students_crm/client/node_modules
      - node-modules:/home/app/students_crm/node_modules
    depends_on:
      - redis
      - postgres
      - react-builder
    environment:
      REDIS_URL: redis
      RAILS_ENV: development
    entrypoint: /home/app/students_crm/bin/start_rails_dev.sh

  react-builder:
    build:
      context: '.'
      dockerfile: docker/akadem_students/Dockerfile
      target: development
    entrypoint: /home/app/students_crm/bin/start_react_dev.sh
    volumes:
      - .:/home/app/students_crm
      - assets-javascript-generated:/home/app/students_crm/app/assets/javascript/generated
      - bundle:/usr/local/bundle/
      - client-node-modules:/home/app/students_crm/client/node_modules
      - node-modules:/home/app/students_crm/node_modules
    entrypoint: /home/app/students_crm/bin/start_react_dev.sh

volumes:
  assets-javascript-generated:
  bundle:
  client-node-modules:
  node-modules:
  postgres-data:
