default: &default
  :concurrency: 10
  :verbose: true
  :queues:
    - urgent
    - default
    - low
    - mailers
  :scheduler:
    :schedule:
      SchedulesNotifierJob:
        cron: '0 30 12 * * * Europe/Kiev'
        queue: low
      ProgramApplicationsReminderJob:
        cron: '0 30 12 * * 2 Europe/Kiev'
        queue: low
  :redis:
    url: redis://redis:6379/0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  :pidfile: ./tmp/sidekiq.pid