default: &default
  :concurrency: 10
  :verbose: true
  :queues:
    - urgent
    - default
    - low
    - mailers
  :schedule:
    SchedulesNotifierJob:
      cron: '0 30 12 * * * Europe/Kiev'
      queue: low

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  :pidfile: ./tmp/sidekiq.pid
